#!/usr/bin/env python3
"""
Complete test of the enhanced tag suggestion system
Shows both existing and new tag suggestions
"""

import os
import sys
import requests
import json
from dotenv import load_dotenv

# Add parent directory to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.models import get_db, Tweet, Tag

load_dotenv()

def test_complete_system():
    """Test the complete tag suggestion system"""
    
    db = next(get_db())
    
    # Find a tweet with no or few tags for better demonstration
    tweet = db.query(Tweet).filter(
        ~Tweet.text.like('RT @%')  # Not a retweet
    ).order_by(Tweet.created_at.desc()).first()
    
    if not tweet:
        print("No suitable tweet found")
        db.close()
        return
    
    # Check existing tags
    existing_tags = db.query(Tag).filter(Tag.tweet_id == tweet.id).all()
    
    print("=" * 80)
    print("ENHANCED TAG SUGGESTION SYSTEM TEST")
    print("=" * 80)
    
    print(f"\n📝 TWEET DETAILS:")
    print(f"  ID: {tweet.id}")
    print(f"  Author: @{tweet.author_username}")
    print(f"  Text: {tweet.text[:150]}...")
    print(f"  Current tags: {[t.tag for t in existing_tags] if existing_tags else 'None'}")
    
    print("\n" + "-" * 80)
    print("Calling Tag Suggestion API...")
    print("-" * 80)
    
    # Call the API
    api_url = f"http://localhost:8000/api/tags/suggest/{tweet.id}"
    
    try:
        response = requests.post(api_url)
        
        if response.status_code == 200:
            data = response.json()
            
            print(f"\n✅ API Response:")
            print(f"  Model: {data.get('model_used', 'Unknown')}")
            print(f"  Total suggestions: {data.get('total_suggestions', 0)}")
            
            # Show existing suggestions
            existing_sugg = data.get('existing_suggestions', [])
            if existing_sugg:
                print(f"\n🔍 EXISTING TAG SUGGESTIONS (Green in UI):")
                print("  These are semantically similar tags already in the database:")
                print("  " + "-" * 60)
                for i, tag in enumerate(existing_sugg, 1):
                    score_pct = tag.get('score', 0) * 100
                    usage = tag.get('usage_count', 0)
                    print(f"  {i}. {tag['tag']:<25} | Similarity: {score_pct:>5.1f}% | Used: {usage:>3}x")
            else:
                print(f"\n🔍 EXISTING TAG SUGGESTIONS: None found")
            
            # Show new suggestions
            new_sugg = data.get('new_suggestions', [])
            if new_sugg:
                print(f"\n✨ NEW TAG SUGGESTIONS (Purple in UI):")
                print("  These are AI-generated tags not yet in the database:")
                print("  " + "-" * 60)
                for i, tag in enumerate(new_sugg, 1):
                    model = tag.get('model', 'unknown')
                    print(f"  {i}. {tag['tag']:<25} | Generated by: {model}")
            else:
                print(f"\n✨ NEW TAG SUGGESTIONS: None generated")
            
            # Show already tagged
            already = data.get('already_tagged', [])
            if already:
                print(f"\n📌 ALREADY TAGGED (Hidden from suggestions):")
                for tag in already:
                    print(f"  • {tag}")
            
            print("\n" + "=" * 80)
            print("UI BEHAVIOR:")
            print("=" * 80)
            print("• Green tags: Existing tags from vector store (with usage counts)")
            print("• Purple tags: New AI-generated tags")
            print("• Hover shows: Similarity score for existing, model for new")
            print("• Users can select from both groups or add custom tags")
            
        else:
            print(f"❌ Error: API returned status {response.status_code}")
            print(response.text)
            
    except Exception as e:
        print(f"❌ Error calling API: {e}")
    
    db.close()
    
    print("\n" + "=" * 80)
    print("SYSTEM FEATURES:")
    print("=" * 80)
    print("✅ Semantic similarity search using OpenAI embeddings")
    print("✅ FAISS vector store with 612 existing tags")
    print("✅ Dual suggestions: existing (reuse) + new (discovery)")
    print("✅ Fallback chain: OpenAI → spaCy → Keywords")
    print("✅ Debug logging explains when/why fallback is used")

if __name__ == "__main__":
    test_complete_system()